platform :ios, "8.0"
pod 'OpenUDID'
pod "REMenu"
pod "Aspects"
pod "IQKeyboardManager"
pod "MGSwipeTableCell"
pod 'ReactiveCocoa'
#pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
pod "MWPhotoBrowser"
pod 'Reachability'
#pod 'FMDB'
use_frameworks!
pod "SDWebImage"
pod 'Alamofire'
#pod "Popover"
#pod 'Result', :git => 'https://github.com/antitypical/Result.git'
pod 'Box'
pod 'CocoaAsyncSocket'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end